name: Helm Lint and Test Charts

on: pull_request

jobs:
  helm-lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: helm-check
        uses: igabaydulin/helm-check-action@0.2.1
        env:
          CHART_LOCATION: ./charts/oracle-example
          CHART_VALUES: ./charts/oracle-example/values.yaml